# Generated by Django 6.0.3 on 2026-03-31 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('km', models.CharField(max_length=50)),
                ('power', models.CharField(max_length=50)),
                ('fuel', models.CharField(max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image_url', models.URLField(max_length=500)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_sold', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('icon_name', models.CharField(help_text='Lucide icon name (e.g. car, shield)', max_length=50)),
                ('titles', models.JSONField(default=dict, help_text='Translations for title')),
                ('descriptions', models.JSONField(blank=True, default=dict, help_text='Translations for description')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo_url', models.URLField(blank=True, max_length=500)),
                ('descriptions', models.JSONField(blank=True, default=dict, help_text='Translations for description')),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='api.service')),
            ],
        ),
    ]
