# Generated by Django 6.0.3 on 2026-03-31 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_car_service_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='airbags',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='climate',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='co2_emissions',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='color_mfr',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='cylinders',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='displacement',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='doors',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='energy_consumption',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_drive',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='equipment',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_consumption',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='interior',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='itp',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='pollution',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='seats',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='series',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='car',
            name='tank',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='towing_braked',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='towing_unbraked',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='weight',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
