# Generated by Django 6.0.3 on 2026-03-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_car_airbags_car_climate_car_co2_emissions_car_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='airbags',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='car',
            name='climate',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='car',
            name='energy_consumption',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_drive',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='car',
            name='equipment',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_consumption',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='car',
            name='interior',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='car',
            name='itp',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='car',
            name='power',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='car',
            name='series',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
