# Generated by Django 6.0.3 on 2026-04-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_car_airbags_alter_car_brand_alter_car_climate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='partner',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
    ]
