# Generated by Django 6.0.3 on 2026-04-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_car_rating_partner_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='service',
        ),
        migrations.AddField(
            model_name='partner',
            name='services',
            field=models.ManyToManyField(related_name='partners', to='api.service'),
        ),
    ]
